format

diff --git a/.github/workflows/build_task.yml b/.github/workflows/build_task.yml
--- a/.github/workflows/build_task.yml
+++ b/.github/workflows/build_task.yml
@@ -10,52 +10,53 @@ jobs:
   analyze:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: subosito/flutter-action@v1
-      with:
-        flutter-version: '1.17.0'
-        channel: 'stable'
-    - name: Flutter analyze
-      run: |
-        result=$(flutter analyze)
-        echo $result
-        if [ $? -ne 0 ]; then
-            errors=$(echo $result | grep -E 'error.+\.dart:\d+:\d+')
-            if [ $? -ne 0 ]; then
-                exit 0
-            fi
-        fi
+      - uses: actions/checkout@v2
+      - uses: subosito/flutter-action@v1
+        with:
+          flutter-version: '1.17.0'
+          channel: 'stable'
+      - name: Flutter analyze
+        run: |
+          result=$(flutter analyze)
+          echo $result
+          if [ $? -ne 0 ]; then
+              errors=$(echo $result | grep -E 'error.+\.dart:\d+:\d+')
+              if [ $? -ne 0 ]; then
+                  exit 0
+              fi
+          fi
   build-android:
     runs-on: ubuntu-latest
     needs: [analyze]
     steps:
-    - uses: actions/checkout@v2
-    - uses: subosito/flutter-action@v1
-      with:
-        flutter-version: '1.17.0'
-        channel: 'stable'
-    - name: Pub get
-      run: flutter pub get
-    - name: Generate google-services.json
-      env:
-        GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
-      run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/android/app/google-services.json
-    - name: Android build
-      run: flutter build apk
+      - uses: actions/checkout@v2
+      - uses: subosito/flutter-action@v1
+        with:
+          flutter-version: '1.17.0'
+          channel: 'stable'
+      - name: Pub get
+        run: flutter pub get
+      - name: Generate google-services.json
+        env:
+          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
+        run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/android/app/google-services.json
+      - name: Android build
+        run: flutter build apk
   build-ios:
     runs-on: macos-latest
     needs: [analyze]
     steps:
-    - uses: actions/checkout@v2
-    - uses: subosito/flutter-action@v1
-      with:
-        flutter-version: '1.17.0'
-        channel: 'stable'
-    - name: Pub get
-      run: flutter pub get
-    - name: Generate google-services.json
-        env:
-          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
-        run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/ios/Runner/GoogleService-Info.plist
-    - name: iOS build
-      run: flutter build ios
+      - uses: actions/checkout@v2
+      - uses: subosito/flutter-action@v1
+        with:
+          flutter-version: '1.17.0'
+          channel: 'stable'
+      - name: Pub get
+        run: flutter pub get
+      - name: Generate google-services.json
+          env:
+            GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
+          run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/ios/Runner/GoogleService-Info.plist
+      - name: iOS build
+        run: flutter build ios
+
