exit 1 when analyze result has error

diff --git a/.github/workflows/build_task.yml b/.github/workflows/build_task.yml
--- a/.github/workflows/build_task.yml
+++ b/.github/workflows/build_task.yml
@@ -16,7 +16,15 @@ jobs:
         flutter-version: '1.17.0'
         channel: 'stable'
     - name: Flutter analyze
-      run: flutter analyze
+      run: |
+        result=$(flutter analyze)
+        echo $result
+        if [ $? -ne 0 ]; then
+            errors=$(echo $result | grep -E 'error.+\.dart:\d+:\d+')
+            if [ $? -ne 0 ]; then
+                exit 0
+            fi
+        fi
   build-android:
     runs-on: ubuntu-latest
     needs: [analyze]
