exit 1

diff --git a/.github/workflows/build_task.yml b/.github/workflows/build_task.yml
--- a/.github/workflows/build_task.yml
+++ b/.github/workflows/build_task.yml
@@ -17,59 +17,60 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: subosito/flutter-action@v1
-        with:
-          flutter-version: '1.17.0'
-          channel: 'stable'
-      - name: Flutter analyze
-        run: ./scripts/analyze.sh
-      - name: Cache bundle
-        uses: actions/cache@v1
-        with:
-          path: vendor/bundle
-          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-gem-
-      - name: Setup Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 2.7.1
-      - name: Danger
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gem install bundler
-          bundle install
-          bundle exec danger
+#      - uses: subosito/flutter-action@v1
+#        with:
+#          flutter-version: '1.17.0'
+#          channel: 'stable'
+#      - name: Flutter analyze
+#        run: ./scripts/analyze.sh
+#      - name: Cache bundle
+#        uses: actions/cache@v1
+#        with:
+#          path: vendor/bundle
+#          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gem-
+#      - name: Setup Ruby
+#        uses: ruby/setup-ruby@v1
+#        with:
+#          ruby-version: 2.7.1
+#      - name: Danger
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          gem install bundler
+#          bundle install
+#          bundle exec danger
 
   build-android:
     if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
     runs-on: ubuntu-latest
     needs: [analyze]
     steps:
-      - uses: actions/checkout@v2
-      - uses: subosito/flutter-action@v1
-        with:
-          flutter-version: '1.17.0'
-          channel: 'stable'
-      - uses: actions/cache@v1
-        with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
-          restore-keys: |
-            ${{ runner.os }}-gradle-
-      - name: Pub get
-        run: flutter pub get
-      - name: Generate google-services.json
-        env:
-          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
-        run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/android/app/google-services.json
-      - name: Android build
-        run: flutter build apk --release
-      - uses: actions/upload-artifact@v2
-        with:
-          name: generated_apk
-          path: ./build/app/outputs/apk/release/app-release.apk
+      - run: exit 1
+#      - uses: actions/checkout@v2
+#      - uses: subosito/flutter-action@v1
+#        with:
+#          flutter-version: '1.17.0'
+#          channel: 'stable'
+#      - uses: actions/cache@v1
+#        with:
+#          path: ~/.gradle/caches
+#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
+#          restore-keys: |
+#            ${{ runner.os }}-gradle-
+#      - name: Pub get
+#        run: flutter pub get
+#      - name: Generate google-services.json
+#        env:
+#          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
+#        run: echo $GOOGLE_SERVICES_BASE64 | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/android/app/google-services.json
+#      - name: Android build
+#        run: flutter build apk --release
+#      - uses: actions/upload-artifact@v2
+#        with:
+#          name: generated_apk
+#          path: ./build/app/outputs/apk/release/app-release.apk
       - name: Create file failure.txt and write 'true' into it
         if: always()
         run: echo ${{ job.status == 'failure' }} > failure.txt
@@ -124,7 +125,7 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - run: echo ${{ needs.build-android.result }}
+      - run: echo ${{ needs.build-android.result == 'failure' }}
       - name: Cache bundle
         uses: actions/cache@v1
         with:
@@ -169,7 +170,6 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-      - run: echo ${{ needs.distribute_app.result == 'failure' }}
       - name: Download file post_message.txt
         uses: actions/download-artifact@v1
         with:
@@ -182,7 +182,8 @@ jobs:
         run: echo "::set-output name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})"
       # 失敗したときのSlackへの通知
       - name: Slack Notification Failure
-        if: ${{ needs.distribute_app.result == 'cancelled' }}
+#        if: ${{ needs.distribute_app.result == 'failure' }}
+        if: ${{ failure() }}
         uses: rtCamp/action-slack-notify@v2.0.1
         env:
           SLACK_CHANNEL: gotties-log
